# Generated by Django 3.2.12 on 2022-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('num', models.IntegerField(verbose_name='거북이 캐릭터 번호')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='사용자 식별 이메일')),
            ],
            options={
                'verbose_name': '유저 거북이 테이블',
                'db_table': 'turtle',
            },
        ),
    ]
